config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/index',        to: 'users#index'
  get  '/signup',      to: 'users#new'
  post '/signup',      to: 'users#create'

  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  get  '/new_event',   to: 'events#new'
  post '/new_event',   to: 'events#create'
  post '/subscribe',   to: 'events#subscribe'

  resources :users
  resources :events do
    get '/users',        to: 'users#index'
    get '/users/invite', to: 'events#invite'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'#, foreign_key: 'user_id'
  has_and_belongs_to_many :attendees, class_name: 'User'

  validates :description, presence: true, length: { minimum: 6 }
  validates :date, presence: true
  validates :place, presence: true

# Vu sur l'url: https://apidock.com/rails/ActiveRecord/NamedScope/ClassMethods/scope
  scope :current, -> {where("date > ?", DateTime.now)}
  scope :past, -> {where("date < ?", DateTime.now)}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_and_belongs_to_many :attended_events, class_name: 'Event'

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :destroy, :subscribe]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.creator = current_user
    if @event.save
      flash.now[:success] = "Success"
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
  end

  def subscribe
    @event.attendees << current_user
    flash.now[:success] = "Tu es bien inscrit"
    redirect_to root_path
  end

  def invite
    @event = Event.find(params[:event_id])
    @user = User.find(params[:id])
    puts @event.inspect
    @event.attendees << @user
    flash.now[:success] = "Cette connaissance a rejoint l'événement"
    redirect_to @event
  end

  def destroy
    @event.destroy
    flash.now[:success] = "L'évènement a été supprimé"
    redirect_to current_user
  end

  private
  def event_params
    params.require(:event).permit(:description, :date, :place, :creator_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash.now[:success] = "Te revoila"
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_path
    else
      flash.now[:danger] = 'Champs incorrect!'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    puts @event.inspect
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Toute l'équipe de Event Brite te souhaite la bienvenue"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    current_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_current_events.html.erb
<table class="table table-bordered" style="color: #FFFFFF">
  <thead>
    <tr>
      <th><b>Lieu</b></th>
      <th><b>Date</b></th>
      <th><b>Créateur</b></th>
      <th><b>Action(s)</b></th>
    </tr>
  </thead>

  <tbody>
    <% @events.current.each do |event| %>
      <tr>
        <td><%= event.place %></td>
        <td><%= event.date.strftime("%d-%b-%Y") %></td>
        <td><%= event.creator.name %></td>
        <% if logged_in? %>
          <td>
            <%= link_to 'Visionner', event, :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"voir" %>
            <%= link_to 'Inviter', event_users_path(event), :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"inviter" %>
          <% if !(event.attendees.include? current_user) %>
            <%= link_to 'Rejoindre',subscribe_path(id: event.id) , :class=>"btn btn-sm btn-outline", :method=>:post, :id=>"joindre" %>
          </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_past_events.html.erb
<table class="table table-bordered" style="color: #FFFFFF">
  <thead>
    <tr>
      <th><b>Lieu</b></th>
      <th><b>Date</b></th>
      <th><b>Créateur</b></th>
      <th><b>Action(s)</b></th>
    </tr>
  </thead>

  <tbody>
    <% if !@events.nil? %>
      <% @events.past.each do |event| %>
        <tr>
          <td><%= event.place %></td>
          <td><%= event.date.strftime("%d-%b-%Y") %></td>
          <td><%= event.creator.name %></td>
          <% if logged_in? %>
          <td><%= link_to 'Visionner', event, :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"voir" %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/events/index.html.erb
<h1 style="color: #CC3300" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444"><b>Y a pas rien laaaaa</b></h1>
<h2 style="color: #CC3300"><b>Les Evènements du moment</b></h2>

<div class="center jumbotron">
  <h3 style="color: #FFFFFF"><b>Evénements à venir</b></h3>

  <% if !@events.current.any? %>
    <div style="color: #FFFFFF"><i>Aucun événement</i></div>
  <% else %>
    <%= render 'events/current_events' %>
  <% end %>
</div>

<div class="center jumbotron">
  <h3 style="color: #FFFFFF"><b>Evénements que tu as loupé</b></h3>
  <br>
  <% if !@events.past.any? %>
    <div style="color: #FFFFFF"><i>Aucun évènement</i></div>
  <% else %>
    <%= render 'events/past_events' %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 style="color: #FF8C00"><b>Crée ton propre Evénement<b></h1>
<h5 style="color: #FF8C00"><b>Allez, jette-toi à l'eau et montre nous que tu es très créatif</b></h5>

<div class="container">
  <div class="Jumbotron" id="Jcreate">
    <h3 style="color: #FFFFFF" id="titre"><b>Remplis tous les champs</b></h3>
    <div class="row">
    <div class="col-md-6 col-md-offset-3" id="formcreate">
      <%= form_for(@event, url: new_event_path) do |f| %>
<br>
        <p style="color: #FFFFFF"><b>lieu :</b></p>
        <%= f.text_field :place, class: 'form-control' %>
<br>
        <p style="color: #FFFFFF"><b>Date :</b></p>
        <%= f.date_field :date, class: 'form-control' %>
<br>
        <p style="color: #FFFFFF"><b>Description :</b></p>
        <%= f.text_area :description, class: 'form-control' %>
<br>
        <input type="submit" class="btn btn-outline" value="Créer l'Evénement" id="btncreatevent">
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<h1 style="color: #CC3300"><b>Ca va être la folie avec tous ces evènements</b></h1>

<div class="center jumbotron" style="color: #FFFFFF">
  <h2><b>Evénement :</b> <i>#<%= @event.id %></i></h2>
  <h4><b>Organisateur :</b> <i><%= @event.creator.name %></i></h4>
  <h4><b>Lieu de l'événement :</b> <i><%= @event.place %></i></h4>
  <h4><b>Date de l'événement :</b> <i><%= @event.date.strftime("%d %B %Y") %></i></h4>
  <h4><b>description de l'événement :</b></h4>
  <h6><li><i><%= @event.description %></i></li></h6>
</div>

<div class="center jumbotron" style="color: #FFFFFF">
  <h3><b>Regarde tout tes fans</b></h3>
  <br>
  <% if !@event.attendees.any? %>
    <div><i>Aucun participant</i></div>
  <% else %>
    <table class="table table-bordered"  style="color: #FFFFFF">
      <thead>
        <tr>
          <th><b>Name</b></th>
          <th><b>Email</b></th>
        </tr>
      </thead>

      <tbody>
        <% @event.attendees.each do |attendee| %>
          <tr>
            <td><%= attendee.name%></td>
            <td><%= attendee.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light" id="navheader">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" id="brand"><b>Marseille Events Brite</b></a>
    <nav>

      <% if logged_in? %>
      <ul class="nav navbar-expand-sm navbar-nav navbar-right">
        <a href="/users" class="btn btn-outline" role="button" id="index1"><b>Liste des Membres</b></a>
        <a href="/events" class="btn btn-outline" role="button" id="index2"><b>Liste des Evénements</b></a>
        <li class="dropdown">
          <a href="#" class="btn btn-outline dropdown-toggle" data-toggle="dropdown" id="drop">
            <b><%=current_user.name %></b>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Accueil", root_path %></li>
              <li class="divider"></li>
            <li><%= link_to "Mon Profil", current_user %></li>
              <li class="divider"></li>
            <li>
              <%= link_to "Se Déconnecter", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <div class="btn-group" style="float: right">
          <a href="/signup" class="btn btn-outline" role="button" id="sign"><b>S'inscrire</b></a>
          <a href="/login" class="btn btn-outline" role="button" id="log"><b>Se connecter</b></a>
        </div>
      <% end %>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body style="background-color: #FFCC66">
    <%= render 'layouts/header'%>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <% if message == :danger %>
          <div class = "w3-panel w3-red">
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          </div>
        <%else%>
          <div class = "w3-panel w3-green">
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1 style="color: #FFFF00"><b><i>THE PLACE TO BE</i></b></h1>

<div class="container">
  <div class="jumbotron" style="color: white">
    <h1><b>Evénements</b></h1>
    <p><i>Rejoins nous pour voir les bons plans du moment.<br>
       Connecte-toi, pour créer tes propres évènements</i></p>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 style="color: #CC3300" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444"><b>Tu n'es pas solo PIPO !!!</b></h1>
<br>
<h4 style="color: #CC3300"><b>Regarde !!! Il n'y a pas dégun ICI</b></h4>

<div class="jumbotron">
  <table class="table table-bordered" style="color: #FFFFFF" id="profil_index">
    <thead>
      <tr>
        <th style="color: #FFFFFF"><b>ID</b></th>
        <th style="color: #FFFFFF"><b>Pseudo</b></th>
        <th style="color: #FFFFFF"><b>Email</b></th>
        <th style="color: #FFFFFF"><b>Action(s)</b></th>
      </tr>
    </thead>
    <tbody>
      <% @users.reject{|user| user == current_user}.each do |user| %>
        <tr>
          <td style="color: #FFFFFF"><%= user.id %></td>
          <td style="color: #FFFFFF"><%= user.name %></td>
          <td style="color: #FFFFFF"><%= user.email %></td>
          <td style="color: #FF8C00">
            <%= link_to "Voir le Profil", user_path(user), :class=>"btn btn-sm btn-outline", :id=>"profil" %>
            <%= link_to 'Inviter', event_users_path(user), :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"inviter" %>
          </td>
        </tr>
      <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1 style="color: #FF8C00"><b>S'enregistrer<b></h1>

<div class="container">
  <div class="Jumbotron" id="Jcreate">
    <h3 style="color: #FFFFFF" id="titre"><b>Remplis tous les champs</b></h3>
    <div class="row">
    <div class="col-md-6 col-md-offset-3" id="formcreate">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'users/form' %>
<br>
        <p style="color: #FFFFFF"><b>Pseudo :</b></p>
        <%= f.text_field :name, class: 'form-control' %>
<br>
        <p style="color: #FFFFFF"><b>Email :</b></p>
        <%= f.email_field :email, class: 'form-control' %>
<br>
        <p style="color: #FFFFFF"><b>Mot de passe :</b></p>
        <%= f.password_field :password, class: 'form-control' %>
<br>
        <p style="color: #FFFFFF"><b>Confirmation :</b></p>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
        <%= f.submit "S'inscrire", class: "btn btn-outline", id: "btncreate" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 style="color: #CC3366"><b><%= current_user.name %></b></h1>
<div class="center jumbotron">
  <h2 style="color: #FFFFFF"><b>Crée ton Event</b></h2>
  <p style="color: #FFFFFF"><b>Balance ton super plan</b></p>
  <% if !current_user.created_events.any? %>
    <div style="color: #FFFFFF"><i>Aucun Evénement</i></div>
    <br>
  <% else %>
  <table class="table table-bordered"  style="color:#FFFFFF">
    <thead>
      <tr>
        <th><b>Date</b></th>
        <th><b>Lieu</b></th>
        <th><b>Evénement</b></th>
        <th><b>Action(s)</b></th>
      </tr>
    </thead>

    <tbody>
      <% current_user.created_events.each do |event| %>
        <tr>
          <td><%= event.date.strftime("%d-%b-%Y") %></td>
          <td><%= event.place %></td>
          <td><%= event.description%></td>
          <td>
            <%= link_to 'Visionner', event, :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"voir" %>
            <%= link_to 'Inviter', event_users_path(event), :class=>"btn btn-sm btn-outline", :method=>:get, :id=>"inviter" %>
            <%= link_to 'Supprimer', event, :class=>"btn btn-sm btn-outline", :method=>:delete, :id=>"Supprimer" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <br>
  <div>
    <%= link_to "Créer un Evénement", new_event_path, class: "btn btn-lg btn-outline", id: "createvent" %>
  </div>
</div>

<br />

<div class="center jumbotron">
  <h2 style="color: #FFFFFF"><b>Evénements qui t'interesse</b></h2>
  <p style="color: #FFFFFF">Je suis chaud comme la braise</p>
  <% if !current_user.attended_events.any? %>
    <div style="color: #FFFFFF"><i>Aucun Evénement</i></div>
  <% else %>
  <table class="table table-bordered" style="color: #FFFFFF">
    <thead>
      <tr>
        <th>Date</th>
        <th>Lieu</th>
        <th>Evénement</th>
        <th>Action(s)</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.attended_events.each do |event| %>
        <tr>
          <td><%= event.date.strftime("%d-%b-%Y") %></td>
          <td><%= event.place %></td>
          <td><%= event.description%></td>
          <td><%= link_to 'Visionner', event, :class=>"btn btn-sm btn-info", :method=>:get, :id=>"voir" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

<div class="center jumbotron">
  <h1 style="color: #FFFFFF"><b>Evènements Passés</b></h1>
  <p style="color: #FFFFFF">Tant pis pour toi</p>
  <% if !current_user.attended_events.past.any? %>
    <div style="color: #FFFFFF"><i>Aucun Evénement</i></div>
  <% else %>
  <table class="table table-bordered" style="color: #FFFFFF">
    <thead>
      <tr>
        <th>Date</th>
        <th>Lieu</th>
        <th>Evénement</th>
        <th>Action(s)</th>
      </tr>
    </thead>

    <tbody>
      <% current_user.attended_events.past.each do |event| %>
        <tr>
          <td><%= event.date.strftime("%d/%b/%Y") %></td>
          <td><%= event.place %></td>
          <td><%= event.description%></td>
          <td><%= link_to 'Visionner', event, :class=>"btn btn-sm btn-info", :method=>:get, :id=>"voir" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>